### ISSUE TITLE
Feature 1: User can log in using their existing Spotify account 

### ISSUE THREAD

**Issue by JoshuaAaronBaker** [JoshuaAaronBaker/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User will be able to log into spotiy securely after they are redirected to accounts.spotify.com.

User can log in using their existing Spotify account 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<

- drag and drop your screenshots below this line -->
![Screen Shot 2022-09-13 at 3 51 41 PM](https://user-images.githubusercontent.com/91937935/190023006-ecb14a95-d9df-47bd-9e5e-f0a5c0029594.png)
!-
![Screen Shot 2022-09-13 at 3 50 04 PM](https://user-images.githubusercontent.com/91937935/190022885-9410d7d7-45ca-4e17-99dd-1849f4904bd9.png)
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server/index.js` to contain code that requests authorization to access data from Spotify when the log in button is clicked.
- [x] This request will include all scopes needed, wait for Spotify to grant access.
- [x] Redirect to accounts.spotify.com where the user will log into their Spotify account.
- [x] Use access token to access resources from the Spotify API.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to render a log in page 
- [x] Component should render a Spotify logo and a button that says LOG IN

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
