### ISSUE TITLE
Issue 2: User can view a home page with their playlists

### ISSUE THREAD

**Issue by JoshuaAaronBaker** [JoshuaAaronBaker/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User will be able to view a homepage populated with their playlists.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able scroll through the homepage and view their playlists.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="607" alt="Screen Shot 2022-09-19 at 11 20 18 AM" src="https://user-images.githubusercontent.com/91937935/191087288-75f2f58a-ae42-4019-8917-0e51956dfc07.png">
<img width="421" alt="Screen Shot 2022-09-19 at 11 19 41 AM" src="https://user-images.githubusercontent.com/91937935/191087292-05d6ad62-2990-4911-8c09-185584767a55.png">

## ✅ Task Lists

> ##### Commit checklist

### ⚡ Client Tasks

- [x] Update the Welcome component to fetch data from spotify using our access token in local storage.
- [x] Build out the render method of our Welcome component 
- [x] Use dummy data to help create styling and determine layout based on the figma
- [x] Use media queries in order to implement response design between mobile and desktop
- [x] Use the data we received from spotify to populate the elements in our render function

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
