### ISSUE TITLE
Issue 3: User can view the contents of the selected playlist  

### ISSUE THREAD

**Issue by JoshuaAaronBaker** [JoshuaAaronBaker/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to see all the songs of a given playlist, displayed on the string.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="650" alt="Screen Shot 2022-09-22 at 10 40 17 AM" src="https://user-images.githubusercontent.com/91937935/191815200-d359fe15-7c94-43a1-bb65-15412e54e9d8.png">
<img width="220" alt="Screen Shot 2022-09-22 at 10 40 39 AM" src="https://user-images.githubusercontent.com/91937935/191815202-892e42d3-0f6c-427d-af48-9e14705fd2f4.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to ...
- [ ] Update `data.sql` to ...

### ⚡ Client Tasks

- [x] Add the playlist id or song id as a prop for each generated item on the home screen.
- [x] Create a handleClick method.
- [x] Inside the handleClick method, grab the id prop of the targeted element and use it to send a request with axios.
- [x] After the promise object is returned, call for the creation of playlist content component.
- [x] Make the component for displaying the items within a pl.
- [x] Use the data gathered from the axios request to populate the page.
- [x] Style the page according to my figma.
- [x] Add media queries to make the page responsive.

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
